# Generated by Django 4.1.1 on 2022-10-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=31, verbose_name="Код группы")),
                (
                    "program_name",
                    models.CharField(
                        max_length=255, verbose_name="Название направления"
                    ),
                ),
                (
                    "enrollment_year",
                    models.PositiveSmallIntegerField(
                        verbose_name="Год начала обучения"
                    ),
                ),
                (
                    "education_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Бакалавриат"),
                            (1, "Магистратура"),
                            (2, "Аспирантура"),
                        ],
                        default=0,
                        verbose_name="Уровень образования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебная группа",
                "verbose_name_plural": "Учебные группы",
            },
        ),
    ]
