# Generated by Django 4.1.1 on 2022-10-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_studygroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="study_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.studygroup",
                verbose_name="Учебная группа",
            ),
        ),
    ]
