# Generated by Django 4.1.1 on 2022-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_study_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="studygroup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна?"),
        ),
    ]
