# Generated by Django 4.1.1 on 2022-10-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_studygroup_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studygroup",
            options={
                "ordering": ("code",),
                "verbose_name": "Учебная группа",
                "verbose_name_plural": "Учебные группы",
            },
        ),
    ]
