# Generated by Django 4.1.1 on 2023-05-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academic_plans", "__first__"),
        ("tasks", "0013_remove_subject_study_group_subject_academic_plan_and_more"),
        ("users", "0007_alter_user_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="study_group",
        ),
        migrations.AddField(
            model_name="user",
            name="academic_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="academic_plans.academicplan",
                verbose_name="Учебный план",
            ),
        ),
        migrations.DeleteModel(
            name="StudyGroup",
        ),
    ]
