# Generated by Django 4.1.1 on 2023-05-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academic_plans", "0003_fieldofstudy_number"),
        ("users", "0008_remove_user_study_group_user_academic_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="academic_plan",
        ),
        migrations.AddField(
            model_name="user",
            name="educational_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="academic_plans.educationalprogram",
                verbose_name="Образовательная программа",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="field_of_study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="academic_plans.fieldofstudy",
                verbose_name="Направление подготовки",
            ),
        ),
    ]
