# Generated by Django 4.1.1 on 2022-10-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_studygroup"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="study_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="users.studygroup",
                verbose_name="Учебная группа",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher_info",
            field=models.TextField(
                blank=True, verbose_name="Информация о преподавателе"
            ),
        ),
    ]
