# Generated by Django 4.1.1 on 2022-10-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_subject_study_group_subject_teacher_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("deadline_at",),
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
            },
        ),
    ]
