# Generated by Django 4.1.1 on 2022-10-03 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.subject",
                verbose_name="Предмет",
            ),
        ),
    ]
