# Generated by Django 4.1.1 on 2022-10-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ("title",),
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
    ]
