# Generated by Django 4.1.1 on 2022-10-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_subject_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Срок выполнения"
            ),
        ),
    ]
