# Generated by Django 4.1.1 on 2022-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_task_deadline_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="links",
            field=models.TextField(blank=True, verbose_name="Ссылки"),
        ),
    ]
