# Generated by Django 4.1.1 on 2022-10-10 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0008_task_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Выполнено пользователями",
            ),
        ),
    ]
