# Generated by Django 4.1.1 on 2022-10-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_task_completed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="teacher_info",
        ),
        migrations.AddField(
            model_name="subject",
            name="additional_info",
            field=models.TextField(
                blank=True, verbose_name="Дополнительная информация"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="assessment_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Экзамен"), (1, "Зачёт"), (2, "Дифференцированный зачёт")],
                default=1,
                verbose_name="Вид контроля",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ФИО преподавателя"
            ),
        ),
    ]
