# Generated by Django 4.1.1 on 2022-10-11 18:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_remove_subject_teacher_info_subject_additional_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="teacher_contacts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=127),
                blank=True,
                null=True,
                size=None,
                verbose_name="Контакты преподавателя",
            ),
        ),
    ]
