# Generated by Django 4.1.1 on 2022-10-12 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_subject_teacher_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="teacher_contacts",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=127),
                blank=True,
                help_text="Несколько значений можно разделить запятой",
                null=True,
                size=None,
                verbose_name="Контакты преподавателя",
            ),
        ),
    ]
