# Generated by Django 4.1.1 on 2023-05-06 09:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academic_plans", "__first__"),
        ("tasks", "0012_alter_subject_teacher_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="study_group",
        ),
        migrations.AddField(
            model_name="subject",
            name="academic_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academic_plans.academicplan",
                verbose_name="Учебный план",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="semesters",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveSmallIntegerField(),
                default=[1],
                size=None,
                verbose_name="Семестры",
            ),
            preserve_default=False,
        ),
    ]
