# Generated by Django 4.1.1 on 2023-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0013_remove_subject_study_group_subject_academic_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="teacher_name",
            field=models.CharField(
                blank=True, max_length=511, verbose_name="ФИО преподавателя"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(max_length=511, verbose_name="Название"),
        ),
    ]
