# Generated by Django 4.1.1 on 2023-05-06 14:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academic_plans", "0004_alter_academicplan_educational_program"),
        ("tasks", "0014_alter_subject_teacher_name_alter_subject_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="academic_plan",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="semesters",
        ),
        migrations.CreateModel(
            name="SubjectInAcademicPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semesters",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(),
                        size=None,
                        verbose_name="Семестры",
                    ),
                ),
                (
                    "academic_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_entries",
                        to="academic_plans.academicplan",
                        verbose_name="Учебный план",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_plan_entries",
                        to="tasks.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет в учебном плане",
                "verbose_name_plural": "Предметы в учебных планах",
            },
        ),
    ]
