# Generated by Django 4.1.1 on 2023-05-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationalProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "enrollment_year",
                    models.PositiveSmallIntegerField(
                        verbose_name="Год начала обучения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Образовательная программа",
                "verbose_name_plural": "Образовательные программы",
            },
        ),
        migrations.CreateModel(
            name="FieldOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Направление подготовки",
                "verbose_name_plural": "Направления подготовки",
            },
        ),
        migrations.CreateModel(
            name="AcademicPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "educational_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_plans",
                        to="academic_plans.educationalprogram",
                        verbose_name="Образовательная программа",
                    ),
                ),
                (
                    "field_of_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_plans",
                        to="academic_plans.fieldofstudy",
                        verbose_name="Направление подготовки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный план",
                "verbose_name_plural": "Учебные планы",
            },
        ),
    ]
