# Generated by Django 4.1.1 on 2023-05-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic_plans", "0002_remove_academicplan_field_of_study_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldofstudy",
            name="number",
            field=models.CharField(default=1, max_length=31, verbose_name="Код"),
            preserve_default=False,
        ),
    ]
