# Generated by Django 4.1.1 on 2023-05-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academic_plans", "0003_fieldofstudy_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicplan",
            name="educational_program",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_plan",
                to="academic_plans.educationalprogram",
                verbose_name="Образовательная программа",
            ),
        ),
    ]
